# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lau12
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-api-users

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:794038228872:table/UserTable

functions:
  createUser:
    handler: src/create.create
    events:
      - httpApi:
          path: /users
          method: post
          
  getAllUsers:
    handler: src/getAll.getAll
    events:
      - httpApi:
          path: /users
          method: get

  updateUser:
    handler: src/update.update
    events:
      - httpApi:
          path: /users/{id}
          method: put

  deleteUser:
    handler: src/delete.delete
    events:
      - httpApi:
          path: /users/{id}
          method: delete

resources: 
      Resources:
        usersTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: UserTable
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
